name: Lint

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Run pre-commit auto-fix
        run: pre-commit run --all-files --show-diff-on-failure || true

      - name: Commit fixes if needed
        run: |
          if [[ `git status --porcelain` ]]; then
            echo "🔧 pre-commit fixed some files, committing..."
            git config --global user.name "github-actions[bot]"
            git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git commit -am "style: auto-fix lint"
            git push
          else
            echo "✅ No changes to commit"
          fi
